/* assembly.h
 *
 * Data structure definitions and function prototypes for 
 * generating target code (assembly) that can run on TM57.
 *
 * This file also contains a detailed discussion of how
 * exactly a quad operation can be turned into a set of
 * assembly codes, without refering to more information other
 * than from the global g_array, which is generated by
 * function gen_code defined in quad.c
 *
 * by Huizhe Li, Master Student, Dartmouth College
 */


