/* token.h
 *
 * Temporarily used as the token definition file.
 * Will be replaced by the file generated by bison.
 *
 * by Huizhe Li, Master Student, Dartmouth College
 */

/* keyword */
#define	ELSE		258
#define IF		259
#define INT		260
#define RETURN		261
#define VOID		262
#define WHILE		263
#define FOR		264
#define DO		265
#define DOUBLE		266
#define	READ		267
#define PRINT		268
#define BREAK		269
#define CONTINUE	270
#define	SWITCH		271
#define CASE		272
#define	DEFAULT		273
#define SIZEOF		274
#define	CONST		275

/* special symbols */

/* Single-character symbols are not assigned with a symbolic name.
 * Instead, the lexer returns its exact ASCII code.
 */

#define EQ		290
#define NEQ	        291
#define INC		292
#define DEC		293
#define	AND		294
#define OR		295
#define LESSEQ		296
#define GRTEREQ		297

/* other tokens */
#define ID		310
#define NUM		311
#define FNUM		312
#define STRING		313

#define OTHER		314	/* stands for all illegal lexemes */
